### ISSUE TITLE
[Bug] Calendar-linked features not working

### ISSUE THREAD

**Issue by bobobobobowahoo** [AjayShanker-geek/owadio#14]
# **🐞 Bug Report**

All calendar-based features - Holidays, Leave and OIL tracker are not able to load, constantly stuck on loading icon. It has been this way for a while, different wifi networks doesn’t fix the issue, neither does reinstalling the app. Thanks for making this app btw!

![IMG_9922](https://github.com/AjayShanker-geek/owadio/assets/161705254/b314a215-3c8b-49a6-bc4b-d366d6c3e6d6)

**Comment by AjayShanker-geek** [comment]
#13 Issue been fix. I will try to push and update this week if possible, cheers.
