### ISSUE TITLE
Date issue in app.

### ISSUE THREAD

**Issue by JacobcobLee** [AjayShanker-geek/owadio#2]
# date not accurate in app

## **media prove**
![Screenshot_20220511-191044](https://user-images.githubusercontent.com/38951755/167836175-d8f82ce8-0925-4cba-983b-c92e7e3d84a6.jpg)
![Screenshot_20220511-191044](https://user-images.githubusercontent.com/38951755/167836205-e231b37e-18fd-4f02-8304-6bae7c4f4fad.jpg)

---

**Comment by AjayShanker-geek** [comment]
The app got approve, so will be closing the issue. Cheers
